---
title: "Mini project 2"
author: "S/18/841"
date: "2024-05-28"
output:
  word_document: default
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load necessary libraries
library(readr)
library(dplyr)
library(CCA)
library(CCP)
```
```{r}
# Load the data
data <- read.csv('../data/Steel_industry_data.csv')
```
```{r}
# View the first few rows and column names of the dataset
head(data)
colnames(data)
```
```{r}
# Select relevant columns for Set 1 and Set 2
data1 <- data %>%
  select(Usage_kWh, Lagging_Current_Reactive.Power_kVarh, Leading_Current_Reactive_Power_kVarh)

data2 <- data %>%
  select(CO2.tCO2., Lagging_Current_Power_Factor, Leading_Current_Power_Factor)
```
```{r}
# Ensure the data is numeric (convert categorical variables if necessary)
data1 <- data1 %>%
  mutate(across(everything(), as.numeric))

data2 <- data2 %>%
  mutate(across(everything(), as.numeric))
```
```{r}
# Check for any missing values
sum(is.na(data1))
sum(is.na(data2))

# Remove any rows with missing values
data1 <- na.omit(data1)
data2 <- na.omit(data2)
```
```{r}
# Standardize the datasets
data1 <- scale(data1)
data2 <- scale(data2)
```
```{r}
# Perform Canonical Correlation Analysis
cc_model <- cancor(data1, data2)
cc_model
```
```{r}
# Extract canonical correlations
rho <- cc_model$cor
rho
```
```{r}
# Number of observations and number of variables in each set
n <- nrow(data)
p <- ncol(data1)
q <- ncol(data2)

```
```{r}
# Perform Wilks' lambda, Hotelling-Lawley trace, Pillai's trace, and Roy's greatest root tests
wilks_result <- p.asym(rho, n, p, q, tstat = "Wilks")
hotelling_result <- p.asym(rho, n, p, q, tstat = "Hotelling")
pillai_result <- p.asym(rho, n, p, q, tstat = "Pillai")
roy_result <- p.asym(rho, n, p, q, tstat = "Roy")
```
```{r}
# Canonical correlations
cc_model$cor[1:3]
```
```{r}
# Squared canonical correlations
cc_model$cor[1:3 ]^2
```
```{r}
# Canonical coefficients for X and Y
cc_model$xcoef
```
```{r}
cc_model$ycoef
```
```{r}
# Compute loadings
loadings <- comput(data1, data2, cc_model)
```
```{r}
# Correlations
loadings$corr.X.xscores
```
```{r}
loadings$corr.Y.yscores
```
```{r}
loadings$corr.X.yscores
```
```{r}
loadings$corr.Y.xscores
```



